# Initial version
# --- !Ups

create table "tasks" (
  "id" int generated by default as identity(start with 1) not null primary key,
  "title" varchar not null,
  "description" varchar,
  "state" varchar not null
);

# --- !Downs

drop table "tasks" if exists;